import type { LiveRoom } from "../shared/types";

export const demoRooms: LiveRoom[] = [
  {
    id: "douyin-midnight-radio",
    platform: "douyin",
    title: "午夜电台 · Live Session",
    anchor: "LiveHub Studio",
    category: "音乐",
    viewers: 12840,
    tags: ["音乐", "夜聊"],
    cover: "linear-gradient(135deg, #2f1b52 0%, #8f4fbd 52%, #f5a5c7 100%)",
    status: "live",
    updatedAt: "刚刚",
    demo: true,
  },
  {
    id: "douyin-night-game",
    platform: "douyin",
    title: "峡谷排位冲刺局",
    anchor: "夜航船长",
    category: "游戏",
    viewers: 8630,
    tags: ["游戏", "排位"],
    cover: "linear-gradient(135deg, #122b3a 0%, #0c7892 55%, #83d5ca 100%)",
    status: "live",
    updatedAt: "2 分钟前",
    demo: true,
  },
  {
    id: "douyu-speedrun",
    platform: "douyu",
    title: "独立游戏速通研究室",
    anchor: "PixelMori",
    category: "游戏",
    viewers: 32600,
    tags: ["速通", "独立游戏"],
    cover: "linear-gradient(135deg, #301b3f 0%, #b44b75 48%, #ffbc7d 100%)",
    status: "live",
    updatedAt: "5 分钟前",
    demo: true,
  },
  {
    id: "douyu-tech-talk",
    platform: "douyu",
    title: "周末硬件拆箱与闲聊",
    anchor: "山海实验室",
    category: "科技",
    viewers: 5980,
    tags: ["科技", "硬件"],
    cover: "linear-gradient(135deg, #14283f 0%, #286b9e 50%, #9bd7e5 100%)",
    status: "live",
    updatedAt: "8 分钟前",
    demo: true,
  },
  {
    id: "huya-chill-room",
    platform: "huya",
    title: "轻松上分 · 不急不躁",
    anchor: "小满同学",
    category: "游戏",
    viewers: 17200,
    tags: ["游戏", "陪伴"],
    cover: "linear-gradient(135deg, #17392f 0%, #2f9b74 50%, #c6e69b 100%)",
    status: "live",
    updatedAt: "1 分钟前",
    demo: true,
  },
  {
    id: "huya-live-talk",
    platform: "huya",
    title: "周五晚间脱口秀",
    anchor: "一颗橘子",
    category: "聊天",
    viewers: 7410,
    tags: ["聊天", "综艺"],
    cover: "linear-gradient(135deg, #3f263e 0%, #d25d7b 52%, #ffc58d 100%)",
    status: "live",
    updatedAt: "11 分钟前",
    demo: true,
  },
  {
    id: "bilibili-desk-stream",
    platform: "bilibili",
    title: "桌面电台：一起写点代码",
    anchor: "蓝色小窗",
    category: "学习",
    viewers: 4360,
    tags: ["学习", "编程"],
    cover: "linear-gradient(135deg, #19304a 0%, #3e8bc1 52%, #b7e5f3 100%)",
    status: "live",
    updatedAt: "3 分钟前",
    demo: true,
  },
  {
    id: "bilibili-acoustic-night",
    platform: "bilibili",
    title: "木吉他与一盏小灯",
    anchor: "南风琴房",
    category: "音乐",
    viewers: 9150,
    tags: ["音乐", "翻唱"],
    cover: "linear-gradient(135deg, #4b2d27 0%, #b96549 48%, #f7d28d 100%)",
    status: "live",
    updatedAt: "6 分钟前",
    demo: true,
  },
];
